---
- hosts: all
  become: yes
  tasks:
    - name: Reset docker setup
      command: sh ./scripts/reset.sh
      args:
        chdir: /opt/blockchain-carbon-accounting/utility-emissions-channel/docker-compose-setup