apiVersion: v1
kind: Service
metadata:
  name: fabric-peer4
  namespace: fabric-peer
spec:
  type: ClusterIP
  ports:
  - port: 7051
    name: port-7051
    targetPort: 7051
  - port: 9443
    name: port-9443
    targetPort: 9443
  selector:
    app: fabric-peer1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-fabric-peer
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0db8aef2f6edd3561
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-peer4
  namespace: fabric-peer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-static-fabric-peer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-peer4
  namespace: fabric-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-peer4
  template:
    metadata:
      labels:
        app: fabric-peer4
    spec:
      containers:
      - name: fabric-peer4
        image: hyperledger/fabric-peer:2.2.1
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 9443
        env:
          #Generic peer variables
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/fabric/crypto-material/msp/
        # Peer specific variabes
        - name: CORE_PEER_ID
          value: fabric-peer4.opensolarx.com
        - name: CORE_PEER_ADDRESS
          value: fabric-peer4.opensolarx.com:443
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_CHAINCODEADDRESS
          value: fabric-peer4.opensolarx.com:443
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: fabric-peer4.opensolarx.com:443
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: fabric-peer4.opensolarx.com:443
        - name: CORE_PEER_LOCALMSPID
          value: opensolarx
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: localhost:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: admin
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: aiG6ohsh6Uch5oot
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:9443
        - name: CORE_METRICS_PROVIDER
          value: prometheus
        # - name: 
        #   value: 
        volumeMounts:
          # - name: cm-configtx-yaml
          #   mountPath: /etc/hyperledger/fabric/configtx.yaml
          #   subPath: configtx.yaml
          - name: opensolarxanchors
            mountPath: /etc/hyperledger/fabric/channel-artifacts/opensolarxanchors.tx
            subPath: opensolarxanchors.tx
          - name: utilityemissionchannel
            mountPath: /etc/hyperledger/fabric/channel-artifacts/utilityemissionchannel.tx
            subPath: utilityemissionchannel.tx
          - name: fabric-peer4-pvc
            mountPath: /var/hyperledger/production
            subPath: production
          - name: fabric-peer4-pvc
            mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
            subPath: peer
          - name: fabric-peer4-pvc
            mountPath: /etc/hyperledger/fabric/crypto-material
            subPath: crypto-material

      - name: couchdb
        image: hyperledger/fabric-couchdb:0.4
        ports:
          - containerPort: 5984
          - containerPort: 4369
          - containerPort: 9100
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: aiG6ohsh6Uch5oot
        volumeMounts:
          - mountPath: /opt/couchdb/data
            name: fabric-peer4-pvc
            subPath: couchdb-data

      initContainers:
        # Extract and mount crypto-config
        - name: init-container-peer
          image: busybox
          command: ['sh', '-c', 'tar zxvf /etc/peer-secret-tgz/peer4-crypto -C /etc/hyperledger/fabric/crypto-material']
          volumeMounts:
              - name: peer4-crypto
                mountPath: /etc/peer-secret-tgz
              - name: fabric-peer4-pvc
                mountPath: /etc/hyperledger/fabric/crypto-material
                subPath: crypto-material
          
      volumes:
      - configMap:
          name: opensolarxanchors
        name: opensolarxanchors
      - configMap:
          name: utilityemissionchannel
        name: utilityemissionchannel
      - secret:
          secretName: peer4-crypto
        name: peer4-crypto
      - persistentVolumeClaim:
          claimName: fabric-peer4
        name: fabric-peer4-pvc