apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-fabric-ca
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-02d6e7b6d6d4f930e