apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-fabric-peer
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0db8aef2f6edd3561